using UnityEngine;
using VRC.SDKBase;

namespace Migimaru.OnOffMenuItemSetupSupporter
{
        [DisallowMultipleComponent]
        public sealed class AutoGeneratedNextPageMarker : MonoBehaviour, IEditorOnly
        {
        }
}
