using UnityEditor;

namespace Migimaru.OnOffMenuItemSetupSupporter.Editor
{
    [CustomEditor(typeof(AutoGeneratedNextPageMarker))]
    public sealed class AutoGeneratedNextPageMarkerEditor
        : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            EditorGUILayout.HelpBox(
                "このComponentはOn/Off Menu Item Setup Supporterが"
                + "自動生成したNextPageを識別するためだけに使用されます。\n"
                + "アバターの動作には影響しません。",
                MessageType.Info
            );
        }
    }
}