using System.Collections.Generic;
using System.Reflection;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using jp.lilxyzw.lilycalinventory.runtime;

namespace Migimaru.OnOffMenuItemSetupSupporter.Editor.Tests
{
    public sealed class ItemTogglerSetupWindowIntegrationTests
    {
        private GameObject rootObject;

        private ItemTogglerSetupWindow window;


        [SetUp]
        public void SetUp()
        {
            Undo.ClearAll();


            rootObject =
                new GameObject(
                    "TestRoot"
                );


            rootObject.AddComponent<MenuFolder>();


            window =
                ScriptableObject.CreateInstance
                    <ItemTogglerSetupWindow>();


            SetPrivateField(
                window,
                "sourceMenuFolder",
                rootObject
            );
        }


        [TearDown]
        public void TearDown()
        {
            Undo.ClearAll();


            if (window != null)
            {
                Object.DestroyImmediate(
                    window
                );
            }


            if (rootObject != null)
            {
                Object.DestroyImmediate(
                    rootObject
                );
            }
        }


        // =========================================================
        // NextPage
        // =========================================================

        [Test]
        public void NextPage生成でMenuFolderとMarkerが付与される()
        {
            GameObject nextPage =
                InvokePrivate<GameObject>(
                    window,
                    "CreateAutoNextPage",
                    rootObject
                );


            Assert.IsNotNull(
                nextPage
            );


            Assert.AreEqual(
                rootObject.transform,
                nextPage.transform.parent
            );


            Assert.IsNotNull(
                nextPage.GetComponent<MenuFolder>()
            );


            Assert.IsNotNull(
                nextPage.GetComponent
                    <AutoGeneratedNextPageMarker>()
            );


            Assert.AreEqual(
                "NextPage",
                nextPage.name
            );
        }


        [Test]
        public void 同名NextPageがある場合はNextPage2になる()
        {
            GameObject manualNextPage =
                new GameObject(
                    "NextPage"
                );


            manualNextPage.transform.SetParent(
                rootObject.transform
            );


            manualNextPage.AddComponent<MenuFolder>();


            GameObject generatedNextPage =
                InvokePrivate<GameObject>(
                    window,
                    "CreateAutoNextPage",
                    rootObject
                );


            Assert.AreEqual(
                "NextPage2",
                generatedNextPage.name
            );


            Assert.AreEqual(
                "NextPage",
                manualNextPage.name
            );


            Assert.IsNull(
                manualNextPage.GetComponent
                    <AutoGeneratedNextPageMarker>()
            );


            Assert.IsNotNull(
                generatedNextPage.GetComponent
                    <AutoGeneratedNextPageMarker>()
            );
        }


        // =========================================================
        // ItemToggler
        // =========================================================

        [Test]
        public void ItemToggler生成で対象Meshが登録される()
        {
            GameObject meshObject =
                CreateMeshObject(
                    "Hat"
                );


            InvokePrivate(
                window,
                "CreateItemToggler",
                meshObject,
                rootObject
            );


            ItemToggler[] togglers =
                rootObject.GetComponentsInChildren
                    <ItemToggler>(true);


            Assert.AreEqual(
                1,
                togglers.Length
            );


            Assert.AreEqual(
                "Hat",
                togglers[0].gameObject.name
            );


            SerializedObject serializedObject =
                new SerializedObject(
                    togglers[0]
                );


            SerializedProperty menuName =
                serializedObject.FindProperty(
                    "menuName"
                );


            Assert.IsTrue(
                string.IsNullOrEmpty(
                    menuName.stringValue
                )
            );


            SerializedProperty parameter =
                serializedObject.FindProperty(
                    "parameter"
                );


            SerializedProperty objects =
                parameter.FindPropertyRelative(
                    "objects"
                );


            Assert.AreEqual(
                1,
                objects.arraySize
            );


            SerializedProperty element =
                objects.GetArrayElementAtIndex(
                    0
                );


            SerializedProperty obj =
                element.FindPropertyRelative(
                    "obj"
                );


            Assert.AreEqual(
                meshObject,
                obj.objectReferenceValue
            );
        }


        [Test]
        public void HideWhenOnではDefaultValueがFalseになる()
        {
            SetSetupMode(
                ItemTogglerSetupMode.HideWhenOn
            );


            GameObject meshObject =
                CreateMeshObject(
                    "Hat"
                );


            InvokePrivate(
                window,
                "CreateItemToggler",
                meshObject,
                rootObject
            );


            ItemToggler toggler =
                rootObject.GetComponentInChildren
                    <ItemToggler>();


            SerializedObject serializedObject =
                new SerializedObject(
                    toggler
                );


            SerializedProperty defaultValue =
                serializedObject.FindProperty(
                    "defaultValue"
                );


            Assert.IsFalse(
                defaultValue.boolValue
            );
        }


        [Test]
        public void HideWhenOffではDefaultValueがTrueになる()
        {
            SetSetupMode(
                ItemTogglerSetupMode.HideWhenOff
            );


            GameObject meshObject =
                CreateMeshObject(
                    "Hat"
                );


            InvokePrivate(
                window,
                "CreateItemToggler",
                meshObject,
                rootObject
            );


            ItemToggler toggler =
                rootObject.GetComponentInChildren
                    <ItemToggler>();


            SerializedObject serializedObject =
                new SerializedObject(
                    toggler
                );


            SerializedProperty defaultValue =
                serializedObject.FindProperty(
                    "defaultValue"
                );


            Assert.IsTrue(
                defaultValue.boolValue
            );
        }


        // =========================================================
        // 実際のページ分割
        // =========================================================

        [Test]
        public void Item7個ならNextPageなしで同一MenuFolderに生成される()
        {
            List<GameObject> meshes =
                CreateMeshObjects(
                    7
                );


            InvokePrivate(
                window,
                "CreateItemsWithPagination",
                rootObject,
                meshes
            );


            Assert.AreEqual(
                7,
                CountDirectItemTogglers(
                    rootObject
                )
            );


            Assert.IsNull(
                FindDirectAutoNextPage(
                    rootObject
                )
            );
        }


        [Test]
        public void Item8個なら6個と2個にページ分割される()
        {
            List<GameObject> meshes =
                CreateMeshObjects(
                    8
                );


            InvokePrivate(
                window,
                "CreateItemsWithPagination",
                rootObject,
                meshes
            );


            Assert.AreEqual(
                6,
                CountDirectItemTogglers(
                    rootObject
                )
            );


            GameObject nextPage =
                FindDirectAutoNextPage(
                    rootObject
                );


            Assert.IsNotNull(
                nextPage
            );


            Assert.AreEqual(
                2,
                CountDirectItemTogglers(
                    nextPage
                )
            );


            Assert.IsNull(
                FindDirectAutoNextPage(
                    nextPage
                )
            );
        }


        [Test]
        public void Item14個なら6個6個2個の3ページになる()
        {
            List<GameObject> meshes =
                CreateMeshObjects(
                    14
                );


            InvokePrivate(
                window,
                "CreateItemsWithPagination",
                rootObject,
                meshes
            );


            Assert.AreEqual(
                6,
                CountDirectItemTogglers(
                    rootObject
                )
            );


            GameObject secondPage =
                FindDirectAutoNextPage(
                    rootObject
                );


            Assert.IsNotNull(
                secondPage
            );


            Assert.AreEqual(
                6,
                CountDirectItemTogglers(
                    secondPage
                )
            );


            GameObject thirdPage =
                FindDirectAutoNextPage(
                    secondPage
                );


            Assert.IsNotNull(
                thirdPage
            );


            Assert.AreEqual(
                2,
                CountDirectItemTogglers(
                    thirdPage
                )
            );


            Assert.IsNull(
                FindDirectAutoNextPage(
                    thirdPage
                )
            );
        }


        [Test]
        public void 子MenuFolder2個とItem6個なら4個と2個に分割される()
        {
            CreateMenuFolderObject(
                "Accessory"
            );


            CreateMenuFolderObject(
                "Shoes"
            );


            List<GameObject> meshes =
                CreateMeshObjects(
                    6
                );


            InvokePrivate(
                window,
                "CreateItemsWithPagination",
                rootObject,
                meshes
            );


            Assert.AreEqual(
                4,
                CountDirectItemTogglers(
                    rootObject
                )
            );


            GameObject nextPage =
                FindDirectAutoNextPage(
                    rootObject
                );


            Assert.IsNotNull(
                nextPage
            );


            Assert.AreEqual(
                2,
                CountDirectItemTogglers(
                    nextPage
                )
            );
        }


        [Test]
        public void 子MenuFolder6個とItem2個なら最初のページはItem0個になる()
        {
            for (int i = 0; i < 6; i++)
            {
                CreateMenuFolderObject(
                    $"Folder{i + 1}"
                );
            }


            List<GameObject> meshes =
                CreateMeshObjects(
                    2
                );


            InvokePrivate(
                window,
                "CreateItemsWithPagination",
                rootObject,
                meshes
            );


            /*
             * 1ページ目:
             *
             * Back
             * Folder x 6
             * NextPage
             *
             * = 8項目
             *
             * したがってItemは0個。
             */
            Assert.AreEqual(
                0,
                CountDirectItemTogglers(
                    rootObject
                )
            );


            GameObject nextPage =
                FindDirectAutoNextPage(
                    rootObject
                );


            Assert.IsNotNull(
                nextPage
            );


            Assert.AreEqual(
                2,
                CountDirectItemTogglers(
                    nextPage
                )
            );
        }


        [Test]
        public void 既存自動NextPageに空きがある場合は前ページの空きを先に使う()
        {
            /*
             * 既存状態:
             *
             * Back
             * Existing1
             * Existing2
             * NextPage
             *
             * なので新規Itemを4個まで
             * 1ページ目へ追加できる。
             */

            CreateItemTogglerObject(
                "Existing1"
            );


            CreateItemTogglerObject(
                "Existing2"
            );


            GameObject existingNextPage =
                InvokePrivate<GameObject>(
                    window,
                    "CreateAutoNextPage",
                    rootObject
                );


            List<GameObject> meshes =
                CreateMeshObjects(
                    5
                );


            InvokePrivate(
                window,
                "CreateItemsWithPagination",
                rootObject,
                meshes
            );


            Assert.AreEqual(
                6,
                CountDirectItemTogglers(
                    rootObject
                )
            );


            Assert.AreEqual(
                1,
                CountDirectItemTogglers(
                    existingNextPage
                )
            );


            Assert.AreEqual(
                existingNextPage,
                FindDirectAutoNextPage(
                    rootObject
                )
            );
        }


        // =========================================================
        // 子MenuFolderの並び順
        // =========================================================

        [Test]
        public void 子MenuFolder上ならFolderがItemTogglerより上になる()
        {
            GameObject itemObject =
                CreateItemTogglerObject(
                    "Item"
                );


            GameObject folderObject =
                CreateMenuFolderObject(
                    "Accessory"
                );


            itemObject.transform.SetSiblingIndex(
                0
            );


            folderObject.transform.SetSiblingIndex(
                1
            );


            SetChildFolderPosition(
                "Top"
            );


            InvokePrivate(
                window,
                "ApplyChildFolderOrder",
                rootObject
            );


            Assert.Less(
                folderObject.transform
                    .GetSiblingIndex(),
                itemObject.transform
                    .GetSiblingIndex()
            );
        }


        [Test]
        public void 子MenuFolder下ならItemTogglerがFolderより上になる()
        {
            GameObject folderObject =
                CreateMenuFolderObject(
                    "Accessory"
                );


            GameObject itemObject =
                CreateItemTogglerObject(
                    "Item"
                );


            folderObject.transform.SetSiblingIndex(
                0
            );


            itemObject.transform.SetSiblingIndex(
                1
            );


            SetChildFolderPosition(
                "Bottom"
            );


            InvokePrivate(
                window,
                "ApplyChildFolderOrder",
                rootObject
            );


            Assert.Less(
                itemObject.transform
                    .GetSiblingIndex(),
                folderObject.transform
                    .GetSiblingIndex()
            );
        }


        [Test]
        public void 自動NextPageは常に最後になる()
        {
            GameObject nextPage =
                InvokePrivate<GameObject>(
                    window,
                    "CreateAutoNextPage",
                    rootObject
                );


            GameObject folderObject =
                CreateMenuFolderObject(
                    "Accessory"
                );


            GameObject itemObject =
                CreateItemTogglerObject(
                    "Item"
                );


            SetChildFolderPosition(
                "Top"
            );


            InvokePrivate(
                window,
                "ApplyChildFolderOrder",
                rootObject
            );


            Assert.Greater(
                nextPage.transform
                    .GetSiblingIndex(),
                folderObject.transform
                    .GetSiblingIndex()
            );


            Assert.Greater(
                nextPage.transform
                    .GetSiblingIndex(),
                itemObject.transform
                    .GetSiblingIndex()
            );
        }


        // =========================================================
        // 上書き削除
        // =========================================================

        [Test]
        public void 自動NextPageだけが削除され手動NextPageは残る()
        {
            GameObject manualNextPage =
                CreateMenuFolderObject(
                    "NextPage"
                );


            GameObject autoNextPage =
                InvokePrivate<GameObject>(
                    window,
                    "CreateAutoNextPage",
                    rootObject
                );


            InvokePrivate(
                window,
                "DeleteAutoGeneratedNextPages"
            );


            Assert.IsTrue(
                manualNextPage != null
            );


            Assert.IsTrue(
                autoNextPage == null
            );
        }


        [Test]
        public void 純粋なItemToggler用GameObjectは上書き削除でObjectごと消える()
        {
            GameObject itemObject =
                CreateItemTogglerObject(
                    "PureItem"
                );


            InvokePrivate(
                window,
                "DeleteExistingItemTogglers"
            );


            Assert.IsTrue(
                itemObject == null
            );
        }


        [Test]
        public void MenuFolder付きObjectは上書き削除でもObjectを保持する()
        {
            GameObject mixedObject =
                new GameObject(
                    "MixedObject"
                );


            mixedObject.transform.SetParent(
                rootObject.transform
            );


            mixedObject.AddComponent<MenuFolder>();

            mixedObject.AddComponent<ItemToggler>();


            InvokePrivate(
                window,
                "DeleteExistingItemTogglers"
            );


            Assert.IsTrue(
                mixedObject != null
            );


            Assert.IsNotNull(
                mixedObject.GetComponent<MenuFolder>()
            );


            Assert.IsNull(
                mixedObject.GetComponent<ItemToggler>()
            );
        }


        [Test]
        public void 他Component付きObjectは上書き削除でもObjectを保持する()
        {
            GameObject mixedObject =
                CreateItemTogglerObject(
                    "MixedObject"
                );


            mixedObject.AddComponent<BoxCollider>();


            InvokePrivate(
                window,
                "DeleteExistingItemTogglers"
            );


            Assert.IsTrue(
                mixedObject != null
            );


            Assert.IsNotNull(
                mixedObject.GetComponent<BoxCollider>()
            );


            Assert.IsNull(
                mixedObject.GetComponent<ItemToggler>()
            );
        }


        [Test]
        public void 子Object付きItemTogglerは上書き削除でも親Objectと子を保持する()
        {
            GameObject itemObject =
                CreateItemTogglerObject(
                    "ItemWithChild"
                );


            GameObject childObject =
                new GameObject(
                    "ManualChild"
                );


            childObject.transform.SetParent(
                itemObject.transform
            );


            InvokePrivate(
                window,
                "DeleteExistingItemTogglers"
            );


            Assert.IsTrue(
                itemObject != null
            );


            Assert.IsTrue(
                childObject != null
            );


            Assert.IsNull(
                itemObject.GetComponent<ItemToggler>()
            );


            Assert.AreEqual(
                itemObject.transform,
                childObject.transform.parent
            );
        }


        // =========================================================
        // Undo
        // =========================================================

        [Test]
        public void NextPage生成をUndoで戻せる()
        {
            Undo.IncrementCurrentGroup();


            int undoGroup =
                Undo.GetCurrentGroup();


            Undo.SetCurrentGroupName(
                "テストNextPage生成"
            );


            InvokePrivate<GameObject>(
                window,
                "CreateAutoNextPage",
                rootObject
            );


            Undo.CollapseUndoOperations(
                undoGroup
            );


            Assert.AreEqual(
                1,
                rootObject.transform.childCount
            );


            Undo.PerformUndo();


            Assert.AreEqual(
                0,
                rootObject.transform.childCount
            );
        }


        [Test]
        public void ItemToggler生成をUndoで戻せる()
        {
            GameObject meshObject =
                CreateMeshObject(
                    "Hat"
                );


            Undo.IncrementCurrentGroup();


            int undoGroup =
                Undo.GetCurrentGroup();


            Undo.SetCurrentGroupName(
                "テストItemToggler生成"
            );


            InvokePrivate(
                window,
                "CreateItemToggler",
                meshObject,
                rootObject
            );


            Undo.CollapseUndoOperations(
                undoGroup
            );


            Assert.AreEqual(
                1,
                rootObject
                    .GetComponentsInChildren
                    <ItemToggler>(true)
                    .Length
            );


            Undo.PerformUndo();


            Assert.AreEqual(
                0,
                rootObject
                    .GetComponentsInChildren
                    <ItemToggler>(true)
                    .Length
            );
        }


        [Test]
        public void Componentだけ削除したItemTogglerもUndoで復元できる()
        {
            GameObject mixedObject =
                new GameObject(
                    "MixedObject"
                );


            mixedObject.transform.SetParent(
                rootObject.transform
            );


            mixedObject.AddComponent<MenuFolder>();

            mixedObject.AddComponent<ItemToggler>();


            Undo.IncrementCurrentGroup();


            int undoGroup =
                Undo.GetCurrentGroup();


            Undo.SetCurrentGroupName(
                "テストItemToggler削除"
            );


            InvokePrivate(
                window,
                "DeleteExistingItemTogglers"
            );


            Undo.CollapseUndoOperations(
                undoGroup
            );


            Assert.IsNull(
                mixedObject.GetComponent<ItemToggler>()
            );


            Assert.IsNotNull(
                mixedObject.GetComponent<MenuFolder>()
            );


            Undo.PerformUndo();


            Assert.IsNotNull(
                mixedObject.GetComponent<ItemToggler>()
            );


            Assert.IsNotNull(
                mixedObject.GetComponent<MenuFolder>()
            );
        }
        [Test]
        public void InactiveでONで非表示なら初期BoolはONで対象値はTrueになる()
        {
            SetSetupMode(
                ItemTogglerSetupMode.HideWhenOn
            );


            GameObject meshObject =
                CreateMeshObject(
                    "Hat"
                );


            meshObject.SetActive(
                false
            );


            InvokePrivate(
                window,
                "CreateItemToggler",
                meshObject,
                rootObject
            );


            ItemToggler toggler =
                rootObject.GetComponentInChildren
                    <ItemToggler>(true);


            SerializedObject serializedObject =
                new SerializedObject(
                    toggler
                );


            SerializedProperty defaultValue =
                serializedObject.FindProperty(
                    "defaultValue"
                );


            Assert.IsTrue(
                defaultValue.boolValue
            );


            SerializedProperty objects =
                serializedObject
                    .FindProperty("parameter")
                    .FindPropertyRelative("objects");


            SerializedProperty value =
                objects
                    .GetArrayElementAtIndex(0)
                    .FindPropertyRelative("value");


            Assert.IsTrue(
                value.boolValue
            );
        }


        [Test]
        public void InactiveでOFFで非表示なら初期BoolはOFFで対象値はTrueになる()
        {
            SetSetupMode(
                ItemTogglerSetupMode.HideWhenOff
            );


            GameObject meshObject =
                CreateMeshObject(
                    "Hat"
                );


            meshObject.SetActive(
                false
            );


            InvokePrivate(
                window,
                "CreateItemToggler",
                meshObject,
                rootObject
            );


            ItemToggler toggler =
                rootObject.GetComponentInChildren
                    <ItemToggler>(true);


            SerializedObject serializedObject =
                new SerializedObject(
                    toggler
                );


            SerializedProperty defaultValue =
                serializedObject.FindProperty(
                    "defaultValue"
                );


            Assert.IsFalse(
                defaultValue.boolValue
            );


            SerializedProperty objects =
                serializedObject
                    .FindProperty("parameter")
                    .FindPropertyRelative("objects");


            SerializedProperty value =
                objects
                    .GetArrayElementAtIndex(0)
                    .FindPropertyRelative("value");


            Assert.IsTrue(
                value.boolValue
            );
        }


        // =========================================================
        // Test用GameObject
        // =========================================================

        private GameObject CreateMeshObject(
            string name
        )
        {
            GameObject meshObject =
                new GameObject(
                    name
                );


            meshObject.transform.SetParent(
                rootObject.transform
            );


            meshObject.AddComponent
                <SkinnedMeshRenderer>();


            return meshObject;
        }


        private List<GameObject> CreateMeshObjects(
            int count
        )
        {
            List<GameObject> meshes =
                new List<GameObject>();


            for (int i = 0; i < count; i++)
            {
                meshes.Add(
                    CreateMeshObject(
                        $"Mesh{i + 1}"
                    )
                );
            }


            return meshes;
        }


        private GameObject CreateMenuFolderObject(
            string name
        )
        {
            GameObject folderObject =
                new GameObject(
                    name
                );


            folderObject.transform.SetParent(
                rootObject.transform
            );


            folderObject.AddComponent<MenuFolder>();


            return folderObject;
        }


        private GameObject CreateItemTogglerObject(
            string name
        )
        {
            GameObject itemObject =
                new GameObject(
                    name
                );


            itemObject.transform.SetParent(
                rootObject.transform
            );


            itemObject.AddComponent<ItemToggler>();


            return itemObject;
        }


        private static int CountDirectItemTogglers(
            GameObject parent
        )
        {
            int count =
                0;


            foreach (
                Transform child
                in parent.transform
            )
            {
                if (
                    child.GetComponent<ItemToggler>()
                    != null
                )
                {
                    count++;
                }
            }


            return count;
        }


        private static GameObject FindDirectAutoNextPage(
            GameObject parent
        )
        {
            foreach (
                Transform child
                in parent.transform
            )
            {
                if (
                    child.GetComponent
                        <AutoGeneratedNextPageMarker>()
                    == null
                )
                {
                    continue;
                }


                if (
                    child.GetComponent<MenuFolder>()
                    == null
                )
                {
                    continue;
                }


                return child.gameObject;
            }


            return null;
        }


        // =========================================================
        // Reflection
        // =========================================================

        private void SetSetupMode(
            ItemTogglerSetupMode mode
        )
        {
            SetPrivateField(
                window,
                "setupMode",
                mode
            );
        }


        private void SetChildFolderPosition(
            string enumName
        )
        {
            FieldInfo field =
                typeof(ItemTogglerSetupWindow)
                    .GetField(
                        "childFolderPosition",
                        BindingFlags.Instance
                        |
                        BindingFlags.NonPublic
                    );


            Assert.IsNotNull(
                field
            );


            object enumValue =
                System.Enum.Parse(
                    field.FieldType,
                    enumName
                );


            field.SetValue(
                window,
                enumValue
            );
        }


        private static void SetPrivateField(
            object target,
            string fieldName,
            object value
        )
        {
            FieldInfo field =
                target.GetType()
                    .GetField(
                        fieldName,
                        BindingFlags.Instance
                        |
                        BindingFlags.NonPublic
                    );


            Assert.IsNotNull(
                field,
                $"Fieldが見つかりません: {fieldName}"
            );


            field.SetValue(
                target,
                value
            );
        }


        private static void InvokePrivate(
            object target,
            string methodName,
            params object[] arguments
        )
        {
            MethodInfo method =
                target.GetType()
                    .GetMethod(
                        methodName,
                        BindingFlags.Instance
                        |
                        BindingFlags.NonPublic
                    );


            Assert.IsNotNull(
                method,
                $"Methodが見つかりません: {methodName}"
            );


            method.Invoke(
                target,
                arguments
            );
        }


        private static T InvokePrivate<T>(
            object target,
            string methodName,
            params object[] arguments
        )
        {
            MethodInfo method =
                target.GetType()
                    .GetMethod(
                        methodName,
                        BindingFlags.Instance
                        |
                        BindingFlags.NonPublic
                    );


            Assert.IsNotNull(
                method,
                $"Methodが見つかりません: {methodName}"
            );


            object result =
                method.Invoke(
                    target,
                    arguments
                );


            return (T)result;
        }
    }
}
